- name: Claudio Briones
  description: |
    Le pagan por liderar a uno de los equipos mas vintage de Lemontech.

    Su habilidad mas preciada es modificar c√≥digo de software legacy y que este no explote.

    "Urgencia" y "Es para ayer" es su mejor compa√±√≠a.

    No le teme a los problemas de facturaci√≥n y disfruta destruyendo Pull Request (algunos dicen que: "La tristeza de otros", alimentan su alma).
  short_name: brionescl
  avatar_url: profiles/cbriones.png
  skills:
    - Aprendiz de React
    - JavaScript
    - CSS
    - PHP
    - PHP Vintage
  links:
    - type: web
      url: http://briones.cl
      username: briones.cl
  personal_quote:
    quote: "it's fine... üî•"
    author: Claudio Briones

- name: Nicol√°s Torres
  description: |
    Ingeniero en Computaci√≥n, reprob√© Introducci√≥n a la Programaci√≥n mi primer semestre, as√≠ que soy una prueba fiable de `Nada es imposible weon' ni una wea'` (https://www.youtube.com/watch?v=MH78sapVA4Q).

    Durante mi formaci√≥n conoc√≠ los robots y la dom√≥tica (alg√∫n d√≠a tendr√© mi propia casa inteligente home-made que me servir√° vino cuando est√© por llegar).

    Me gusta programar, pero prefiero m√°s pensar en crear buenas soluciones y hacer las cosas bien a la primera. Por lo mismo hice un Diplomado en Gesti√≥n y Evaluaci√≥n de Proyectos TI.

    √öltimamente me he enfocado en apoyar integraciones desde y hacia TB, es m√°s tengo reuni√≥n en unos minutos m√°s.
  short_name: ntorresj
  avatar_url: profiles/ntorres.png
  skills:
    - PHP (old school y FW)
    - Aprend√≠ que una buena soluci√≥n no tiene lenguaje
    - ¬øjQuery a√∫n cuenta?
    - Aportar con buenas soluciones
  links:
    - type: github
      url: https://github.com/ntorresj
      username: ntorresj
  personal_quote:
    quote: "Sin embargo"
    author: Nicol√°s Torres

- name: Gabriel Wurman
  description: |
    Ingeniero TI de la PUC, actualmente desarrollador de software.

    Apasionado por la Ingenier√≠a de Software.
  short_name: gwurman
  avatar_url: profiles/gwurman.png
  skills:
    - NodeJS
    - PHP
    - C#
    - RoR
    - React
    - Ingenier√≠a de Software
  links:
    - type: github
      url: https://github.com/gwurman
      username: gwurman
  personal_quote:
    quote: "La vida es una fiesta y yo soy la pi√±ata."
    author: Gabriel Wurman

- name: Sebasti√°n Gonz√°lez
  description: |
    Actualmente desarrollador web, amante de la computaci√≥n f√≠sica y los robots. En sus a√±os de estudiante se dedic√≥ al mundo de Software Libre llegando a ser parte de la comunidad chilena de Debian.

    Inquieto por naturaleza siempre en busqueda de nuevos conocimientos y hobbies. Desde hace 1 a√±o practica el complejo arte del cambio de pa√±ales y esquivar combos y patadas nocturnas.

    Amante del buen rock y la cerveza, a menudo se escapa a bares a disfrutar de m√∫sica en vivo.
  short_name: frutal
  avatar_url: profiles/sgonzalez.png
  skills:
    - Aprendiz de React
    - Angular
    - JavaScript
    - CSS
    - PHP
    - NodeJS
  links:
    - type: github
      url: https://github.com/brutalchrist
      username: brutalchrist
  personal_quote:
    quote: "La hiciste llorar y yo llor√© y Maggie ri√≥ y todo fue una confusi√≥n."
    author: "Homero J. Simpson"

- name: Gerald Lara
  description: |
    Ingeniero entusiasta de lo simple, le apasiona desarrollar soluciones amigables a las personas para hacer su vida m√°s sencilla y eficiente.

    Es un convencido de que todo se puede aprender y mejorar, por ello divide su tiempo desarrollando software, haciendo m√∫sica, leyendo libros, generando ideas y compartiendo todo esto con los dem√°s.

    Oriundo de la ciudad del Trueno y Ranguerino por herencia y tradici√≥n.

  short_name: glara
  avatar_url: profiles/glara.png
  skills:
    - RoR
    - PHP
    - Javascript
    - React
    - FIFA
  links:
    - type: github
      url: https://github.com/glara
      username: glara
  personal_quote:
    quote: "A path is only a path, and there is no affront, to oneself or to others, in dropping it if that is what your heart tells you... Look at every path closely and deliberately. Try it as many times as you think necessary. Then ask yourself alone, one question... Does this path have a heart? If it does, the path is good; if it doesn't it is of no use."
    author: "Carlos Castaneda"

- name: V√≠ctor S√°nchez
  description: |
    Ingeniero en computaci√≥n, se supone que Full-Stack, me gusta implementar soluciones que agreguen valor al software y a nuestros clientes.

    Actualmente formo parte del equipo de TBX.

    Campe√≥n vigente del √∫nico torneo de FIFA.

    Tambi√©n cumplo el rol de FIFA Technical Leader.
  short_name: vitoco
  avatar_url: profiles/vsanchez.png
  skills:
    - Ruby
    - Javascript
    - ROR
    - React
    - FIFA
  links:
    - type: github
      url: https://github.com/Vsanchezr
      username: Vsanchezr
    - type: linkedin
      url: https://www.linkedin.com/in/vlsanchezr/
      username: vlsanchezr
  personal_quote:
    quote: "No hay que justificar ni satanizar. Hay que tomar conciencia de implementar un cambio. Hay que tener autocr√≠tica para mejorar."
    author:

- name: Claudio Peralta
  description:
  short_name: cuayocps
  avatar_url: profiles/cperalta.png
  skills:
  links:
  personal_quote:

- name: Andr√©s Arellano
  description: |
    Actualmente CTO de Lemontech.

    Es Ingeniero TI de la PUC en Chile, y Mag√≠ster en Ingenier√≠a de Sistemas de la University of Maryland en Estados Unidos.

    Su trayectoria ha estado principalmente marcada por proyectos de innovaci√≥n digital, fomento al emprendimiento en la industria del software y modernizaci√≥n del sector p√∫blico a trav√©s del gobierno digital.

    Ha sido docente de la Universidad de Chile e investigador en el Centro de Estudios de Tecnolog√≠as de la Informaci√≥n de la PUC.

    Apasionado por construir valor para las personas utilizando las tecnolog√≠as de la informaci√≥n.

    Ciclista urbano, padre de tres ni√±as y fan√°tico de las monta√±as.
  short_name:
  avatar_url: profiles/aarellano.png
  skills:
    - Liderazgo de equipos
    - Definici√≥n de estrategia
    - Desarrollo de productos
    - Arquitectura de software
  links:
    - type: github
      url: https://github.com/aarellano
      username: aarellano
    - type: linkedin
      url: https://www.linkedin.com/in/aarellanor/
      username: aarellanor
    - type: twitter
      url: https://twitter.com/aarellanor
      username: "aarellanor"

  personal_quote:
    quote: "There are only two ways to live your life: as though nothing is a miracle, or as though everything is a miracle"
    author: "A. Einstein"

- name: Abraham Barrera
  description: |
    Desarrollador por vocaci√≥n, apasionado por el c√≥digo desde hace 20 a√±os, los cuales ha dedicado al desarrollo web y m√≥vil, adquiriendo la capacidad de desenvolverse en todo el stack tecnol√≥gico.

    Gracias a su curiosidad y la convicci√≥n de querer hacer las cosas bien, siempre ha tenido que liderar equipos donde ha trabajado, sin embargo, lo que le apasiona realmente es la programaci√≥n y la ciencia, esperando alg√∫n d√≠a poder hackear la matrix y liberarlos a todos.

    Santiaguino y m√∫sico de coraz√≥n, no soporta el exceso de gente pero tampoco la paz absoluta durante tiempo prolongado, pasa su tiempo libre con su familia y tocando buena m√∫sica.

  short_name: el capi
  avatar_url: profiles/abarrera.png
  skills:
    - Ruby
    - Javascript
    - Ruby on Rails
    - Java
    - Arquitectura de software
    - Liderazgo t√©cnico
  links:
    - type: github
      url: https://github.com/a-bx
      username: a-bx
    - type: linkedin
      url: https://www.linkedin.com/in/abrahambarrera/
      username: abrahambarrera
    - type: twitter
      url: https://twitter.com/abraham_barrera
      username: "abraham_barrera"

  personal_quote:
    quote: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand."
    author: "Martin Fowler"

- name: Daniel Ochoa
  description: |
    Daniel despert√≥ su pasi√≥n por el c√≥digo a los 10 a√±os, cuando muy enojado porque no le compraban juegos de video, decidi√≥ desarrollarlos el mismo. Santiaguino con sangre sure√±a y colocolino de coraz√≥n, es ingeniero y mag√≠ster en ingenier√≠a inform√°tica de la Universidad de Santiago. A los 21 a√±os fue becado por Google y se fue a Nueva York.

    Cuenta con 8 a√±os de experiencia formales en los que se ha enfocado en hacer crecer productos desde el dise√±o y desarrollo de software, refactorizaciones, estrategia y liderazgo. Ama la tecnolog√≠a y no pierde oportunidad de ense√±arla a otros participando activamente en workshops, charlas y meetups.

    Cuando no est√° programando, probablemente est√© jugando juegos de mesa, algun buen JRPG o FIFA.
  short_name: dochoaj
  avatar_url: profiles/dochoa.png
  skills:
    - Ruby
    - Javascript
    - Java
    - Arquitectura y dise√±o de software
    - Liderazgo t√©cnico
    - Speaker
  links:
    - type: github
      url: https://github.com/dochoaj
      username: dochoaj
    - type: linkedin
      url: https://www.linkedin.com/in/juanochoajohn/
      username: juanochoajohn
    - type: twitter
      url: https://twitter.com/dochoaj
      username: "dochoaj"

  personal_quote:
    quote: "El trabajo duro nunca te traiciona"
    author:

- name: Andr√©s Lazo
  description: |
    Ingeniero de DUOC UC recientemente egresado.

    Posee pasi√≥n por el desarrollo web y por la b√∫squeda de la satisfacci√≥n de cada cliente y miembro del equipo.
  short_name: balazo
  avatar_url: profiles/alazo.png
  skills:
    - Ingresando a Rails y React
  links:
    - type: github
      url: https://github.com/andreslazo
      username: andreslazo
    - type: linkedin
      url: https://www.linkedin.com/in/amlazo/
      username: amlazo

  personal_quote:
    quote: "Seguramente lo vamos a lograr"
    author:

- name: Rodrigo D√≠az
  description: |
    Ingeniero orientado principalmente al dise√±o e implementaci√≥n de aplicaciones web, siempre preocupado de lograr un buen balance entre estilo y experiencia de usuario.

    La programaci√≥n es su pasi√≥n y constantemente est√° en busca de desaf√≠os t√©cnicos y profesionales. Le motiva aprender nuevas tecnolog√≠as, contribuir a la comunidad open source y desarrollar aplicaciones que entreguen valor a sus usuarios.

    Si no est√° programando est√° dedic√°ndole tiempo a su perrito Devin üê∂, tocando bajo con su banda o jugando juegos de mesa con amigos.
  short_name: Erre
  avatar_url: profiles/rdiaz.png
  skills:
    - React
    - React Native
    - Electron
    - CSS
    - Ruby
    - NodeJS
    - Go
  links:
    - type: github
      url: https://github.com/rdiazv
      username: rdiazv
    - type: linkedin
      url: https://www.linkedin.com/in/rdiazv/
      username: rdiazv
    - type: medium
      url: "https://medium.com/@rdiazv"
      username: "rdiazv"

  personal_quote:
    quote: "Trabajo remoto üè° üòÅ"
    author:

- name: Javier L√≥pez
  description: |
    Ingeniero Civil en Computaci√≥n de la PUC.

    Antes de titularse lo invitaron a conocer Lemontech y 10 a√±os despu√©s todav√≠a no sabe c√≥mo escapar.

    Habla fluidamente espa√±ol, ingl√©s, italiano y expresiones regulares.
  short_name: ameboide
  avatar_url: profiles/jlopez.png
  skills:
    - Ruby
    - C#
    - PHP
    - Javascript
    - Java
    - Y sus respectivos frameworks t√≠picos
  links:
    - type: github
      url: https://github.com/ameboide
      username: ameboide
  personal_quote:
    quote: "I'm So Meta, Even This Acronym"
    author: "xkcd citando a Douglas Hofstadter"

- name: Alfonso Guzm√°n
  description: |
    Entry Software Engineer en Lemontech e Ingeniero Civil Inform√°tico de la USACh. En su corta trayector√≠a se ha desempe√±ado como desarrollado Full-Stack. Fue profesor de c√°tedra y laboratorio en la Universidad de Santiago de Chile. Motivado por el constante aprendizaje, el trabajo colaborativo y la construcci√≥n de productos de software que mejoren la calidad de vida de las personas.

    Nunca limitado por su formaci√≥n, le apasiona la lectura que lo ayude a comprender nuestra historia y la sociedad.

    Los animales son sus amigos, no su comida
  short_name: Alfito
  avatar_url: profiles/aguzman.png
  skills:
    - Ruby
    - Java
    - RoR
    - JavaScript
  links:
    - type: medium
      url: https://medium.com/@alfit0
      username: "alfit0"
    - type: linkedin
      url: https://www.linkedin.com/in/aguzmanalv/
      username: aguzmanalv

  personal_quote:
    quote: "El √©xito es deformante, relaja, enga√±a, nos vuelve peor, nos ayuda a enamorarnos excesivamente de nosotros mismos; el fracaso es todo lo contrario, es formativo, nos vuelve s√≥lidos, nos acerca a las convicciones, nos vuelve coherentes."
    author: "Marcelo Bielsa"

- name: Javier Segovia
  description:
  short_name:
  avatar_url: profiles/jsegovia.png
  skills:
  links:
  personal_quote:

- name: Vladimir Zurita
  description: |
    Analista Programador del DUOC, sus pasiones son programar, la m√∫sica y la electr√≥nica.

    Usuario incondicional de Liinux con Gnome.

    Le gusta probar nuevas tecnolog√≠as y aprender constantemente, especialmente de la experiencia de sus compa√±eros.

    Un pionero en el trabajo full remoto en Lemontech traslad√≥ su vida completa a Villarrica, esto ha servido para demostrar que s√≠ se puede.
  short_name: vladzur
  avatar_url: profiles/vzurita.png
  skills:
    - PHP
    - Laravel
    - VueJS
    - Ionic
    - Aprendiz de NodeJS y React
  links:
    - type: twitter
      url: https://twitter.com/vladzur
      username: vladzur
    - type: linkedin
      url: https://www.linkedin.com/in/vladimir-zurita-manquian
      username: vladimir-zurita-manquian

  personal_quote:
    quote: "Que estay mirando..."
    author:

- name: Paula Madariaga
  description: |
    Ingeniero Comercial, USACH. Diplomado en Gesti√≥n de la Innovaci√≥n, Universidad de Chile. Certificaci√≥n CSPO (Kleer)
  short_name: pvmadar
  avatar_url: profiles/pmadariaga.png
  skills:
    - Metodolog√≠a √°gil
    - Scrum
    - Dise√±o y desarrollo de productos
    - Innovaci√≥n
    - E-commerce
    - Gesti√≥n proyectos
  links:
  personal_quote:

- name: Giannina Giannecchini
  description: |
    Desarrolladora full-stack, especializada en tecnolog√≠as Microsoft hasta que Javascript lleg√≥ a su coraz√≥n conquistando el lado Front.

    Entusiasta por la innovaci√≥n le encanta desarrollar soluciones para poder facilitar y acelerar los procesos de trabajo.
  short_name: nina
  avatar_url: profiles/ggiannecchini.png
  skills:
    - C#
    - Javascript
    - React
    - React-Native
    - Arquitectura
    - Speaker
    - Eterna aprendiz
  links:
    - type: linkedin
      url: https://www.linkedin.com/in/giannina-giannecchini-aravena-45825011b/
      username: giannina-giannecchini-aravena
  personal_quote:

- name: √Ångelo Calvo
  description: |
    Desarrollador full-stack autodidacta y amante de la tecnologia desde que tengo uso de razon. Comence a temprana edad con un Atari y Basic, destruyendo mis computadoras y posteriormente reparandolas, lo que poco a poco fue acercandome a este apasionante mundo. Mi lenguaje escuela fue PHP y posteriormente fui migrando a otras tecnologias y posibilidades que no solo se limitaban al software, sino que tambi√©n a la infraestructura, la rob√≥tica y automatizaci√≥n.

    A nivel acad√©mico, en alg√∫n momento de mi vida, ‚Äúme obligaron y me obligue‚Äù a cursar Ingenier√≠a Civil Inform√°tica, y actualmente me desempe√±o como profesor de la Escuela de Ingenier√≠a Civil Inform√°tica de la USS.

    Soy ES lover, en todas sus dimensiones, alucino con la arquitectura de software y me apasiona la construcci√≥n de soluciones tecnol√≥gicas innovadoras, as√≠ como el emprendimiento digital.

    Soy amante del motociclismo de velocidad, la mec√°nica y todo lo que haga rum y suene bonito. Me encata leer para aprender cosas nuevas  y me obsesiona todo lo realcionado al Bio-hacking. Tambi√©n juego a ser Chef de vez en cuando, fabricar cerveza y disfrutar de una vida tranquila.
  short_name: dorian
  avatar_url: profiles/acalvo.png
  skills:
    - Desarrollo de software
    - ES
    - Angular
    - React
    - Nativescript
    - JAVA
    - C++
    - ROR
    - PHP
    - Geodesarrollo
    - Arquitectura de Software
    - Profesor
    - Piloto de velocidad
  links:
    - type: github
      url: https://www.github.com/acalvoa
      username: acalvoa
    - type: linkedin
      url: https://www.linkedin.com/in/angelo-alejandro-calvo-alfaro/
      username: angelo-alejandro-calvo-alfaro

  personal_quote:
    quote: "Dormir... Es parte esencial del proceso creativo"
    author: "Dici√©ndolo despues de haberse quedado dormido sobre el teclado"
